### ISSUE TITLE
React Split Grid doesn't work with React 16.8.0 

### ISSUE THREAD

**Issue by coreybruyere** [nathancahill/split#185]
Are there any live demo's for React Split Grid? Getting `Failed prop type: Invalid prop 'component' of type 'function' supplied to 'ReactSplitGrid', expected a single ReactElement' ` locally when using the component method mentioned in the docs. 

Having issues trying to set up a basic prototype. Can I get a helping hand? 
https://codesandbox.io/s/qq7w2np724

**Comment by coreybruyere** [comment]
Have the same thing working here: https://codesandbox.io/s/38nnmm25y5

Only difference is the working one is on React 16.0 and non-working is on 16.8.0

**Comment by karollewandowski** [comment]
Hi, @coreybruyere , did you solve the problem? It still doesn't work with React 16.8.0 or the currently newest 16.13.1. I can see that issue is closed, so maybe you resolved it. If not, maybe it's worth to reopen?

**Comment by Omnidon** [comment]
I am getting this issue if I use react-split-grid on v16.13.1 of React

It occurs if you use even the sample code provided in the react-split-grid readme for either the component property or the children property.
It doesn't happen if you use the render property

This appears to be due to the fact that component and children are validating using the PropTypes module to verify that they are a single react.element
while render is permitted to output any ReactNode

PropTypes is apparently not recognizing a JSX Element as a single element if it has any children.
